title = "Where I was that day"
character = "Joe"
alias = "test1"

[[statements]]
text = "I remember the day of the crime as if it was yesterday."

[[statements]]
text = "I was hiking alone in the mountains, morning to evening."
objection = "famp"

[[statements]]
text = "It was ![very refreshing], listening the birds and breathing the fresh air. You could do that ![more often] you know!"